// Code generated by "stringer -type PriorityQueueType"; DO NOT EDIT.

package priorityqueue

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MinQueue-1]
	_ = x[MaxQueue-2]
}

const _PriorityQueueType_name = "MinQueueMaxQueue"

var _PriorityQueueType_index = [...]uint8{0, 8, 16}

func (i PriorityQueueType) String() string {
	i -= 1
	if i >= PriorityQueueType(len(_PriorityQueueType_index)-1) {
		return "PriorityQueueType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PriorityQueueType_name[_PriorityQueueType_index[i]:_PriorityQueueType_index[i+1]]
}
